import Layout from "@/component/Layout";
import Head from "next/head";
import React, { useMemo } from "react";
import styles from "@/styles/Profile.module.scss";
import Link from "next/link";
import { FiUser } from "react-icons/fi";
import { HiOutlineClipboardDocumentList } from "react-icons/hi2";
import { useRouter } from "next/router";
import { useCheckAuth } from "@/utils/useCheckAuth";
import { BsInfoCircle, BsPostcard } from "react-icons/bs";
import { FaList, FaUserPlus } from "react-icons/fa";
import { GiBank } from "react-icons/gi";
import { TbReport } from "react-icons/tb";
const ProfileLayout = ({ children }) => {
  const router = useRouter();
  const { user, loading } = useCheckAuth();

  const pathname = useMemo(() => {
    return router.pathname.split("/").pop();
  }, [router.pathname]);

  return (
    <Layout>
      <Head>
        <title>TRAFFIC SEO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 py-5" style={{ minHeight: "100vh" }}>
        <div className="d-flex justify-content-center">
          {loading || (!loading && !user) ? (
            <></>
          ) : (
            <div className="row col-11">
              <div className="col-2  bg-white rounded p-2">
                <div className={`${styles["menu-dropdown"]}`}>
                  <Link
                    href="/profile"
                    style={{
                      color:
                        pathname === "profile" ? "cornflowerblue" : "inherit",
                    }}
                    className={`d-flex align-items-center p-2 ${
                      styles["profile-item"]
                    } ${
                      pathname === "profile"
                        ? styles["profile-item-select"]
                        : ""
                    }`}
                  >
                    <div className="p-1">
                      <HiOutlineClipboardDocumentList size={24} />
                    </div>
                    <div className="p-1">
                      <span>Quản lý yêu cầu</span>
                    </div>
                  </Link>
                </div>
                <div className={styles["menu-dropdown"]}>
                  <Link
                    href="/profile/invitedUser"
                    style={{
                      color:
                        pathname === "invitedUser"
                          ? "cornflowerblue"
                          : "inherit",
                    }}
                    className={`d-flex align-items-center p-2 ${
                      styles["profile-item"]
                    } ${
                      pathname === "invitedUser"
                        ? styles["profile-item-select"]
                        : ""
                    }`}
                  >
                    <div className="p-1">
                      <FaUserPlus size={24} />
                    </div>
                    <div className="p-1">
                      <span>Người dùng đã mời</span>
                    </div>
                  </Link>
                </div>
                {user?.acceptPost === true && (
                  <div className={styles["menu-dropdown"]}>
                    <Link
                      href="/profile/posts"
                      style={{
                        color:
                          pathname === "posts" ? "cornflowerblue" : "inherit",
                      }}
                      className={`d-flex align-items-center p-2 ${
                        styles["profile-item"]
                      } ${
                        pathname === "posts"
                          ? styles["profile-item-select"]
                          : ""
                      }`}
                    >
                      <div className="p-1">
                        <BsPostcard size={24} />
                      </div>
                      <div className="p-1">
                        <span>Bài viết của bạn</span>
                      </div>
                    </Link>
                  </div>
                )}
                <div className={styles["menu-dropdown"]}>
                  <Link
                    href="/profile/point"
                    style={{
                      color:
                        pathname === "point" ? "cornflowerblue" : "inherit",
                    }}
                    className={`d-flex align-items-center p-2 ${
                      styles["profile-item"]
                    } ${
                      pathname === "point" ? styles["profile-item-select"] : ""
                    }`}
                  >
                    <div className="p-1">
                      <BsInfoCircle size={24} />
                    </div>
                    <div className="p-1">
                      <span>Lịch sử điểm</span>
                    </div>
                  </Link>
                </div>

                <div className={styles["menu-dropdown"]}>
                  <Link
                    href="/profile/user"
                    style={{
                      color: pathname === "user" ? "cornflowerblue" : "inherit",
                    }}
                    className={`d-flex align-items-center p-2 ${
                      styles["profile-item"]
                    } ${
                      pathname === "user" ? styles["profile-item-select"] : ""
                    }`}
                  >
                    <div className="p-1">
                      <FiUser size={24} />
                    </div>
                    <div className="p-1">
                      <span>Trang cá nhân</span>
                    </div>
                  </Link>
                </div>
                {/* <div>
                  {pathname === "user" && (
                    <div className="pb-3" style={{ paddingLeft: "3.5rem" }}>
                      <Link
                        href="/profile/user"
                        style={{
                          color:
                            pathname === "user" ? "cornflowerblue" : "inherit",
                        }}
                        className={`d-block mb-2 px-4 mt-2 w-75 p-1 ${
                          styles["profile-item"]
                        } ${
                          pathname === "user"
                            ? styles["profile-item-select"]
                            : ""
                        }`}
                      >
                        Hồ sơ
                      </Link>
                    </div>
                  )}
                </div> */}
                {user?.acceptPost === true && (
                  <div className={styles["menu-dropdown"]}>
                    <Link
                      href="/profile/report"
                      style={{
                        color:
                          pathname === "report" ? "cornflowerblue" : "inherit",
                      }}
                      className={`d-flex align-items-center p-2 ${
                        styles["profile-item"]
                      } ${
                        pathname === "report"
                          ? styles["profile-item-select"]
                          : ""
                      }`}
                    >
                      <div className="p-1">
                        <TbReport size={24} />
                      </div>
                      <div className="p-1">
                        <span>Thống kê</span>
                      </div>
                    </Link>
                  </div>
                )}

                <div className={styles["menu-dropdown"]}>
                  <Link
                    href="/profile/report-payment"
                    style={{
                      color:
                        pathname === "report-payment"
                          ? "cornflowerblue"
                          : "inherit",
                    }}
                    className={`d-flex align-items-center p-2 ${
                      styles["profile-item"]
                    } ${
                      pathname === "report-payment"
                        ? styles["profile-item-select"]
                        : ""
                    }`}
                  >
                    <div className="p-1">
                      <TbReport size={24} />
                    </div>
                    <div className="p-1">
                      <span>Thống kê thanh toán</span>
                    </div>
                  </Link>
                </div>

                <div className={styles["menu-dropdown"]}>
                  <Link
                    href="/profile/payment"
                    style={{
                      color:
                        pathname === "payment" ? "cornflowerblue" : "inherit",
                    }}
                    className={`d-flex align-items-center p-2 ${
                      styles["profile-item"]
                    } ${
                      pathname === "payment"
                        ? styles["profile-item-select"]
                        : ""
                    }`}
                  >
                    <div className="p-1">
                      <GiBank size={24} />
                    </div>
                    <div className="p-1">
                      <span>Liên kết ngân hàng</span>
                    </div>
                  </Link>
                </div>
              </div>
              <div className={`col-10`}>{children}</div>
            </div>
          )}
        </div>
      </main>
    </Layout>
  );
};

export default ProfileLayout;
